language: cpp

compiler:
  - gcc

before_install:
  #- sudo apt-get install valgrind

  # g++4.8.1
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # - sudo apt-get install -qq libboost1.48-dev libboost-test1.48-dev

  # g++4.8.1
  - sudo apt-get install -qq g++-4.8
  - sudo apt-get install -qq libstdc++6-4.7-dev

script: 
  - echo "Lancement des tests"
  - make gcc-test
  #- valgrind --leak-check=full --show-reachable=yes ../bin/quasar
